---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logtrail-config
  namespace: staging
data:
  logtrail.json: |
    {
      "index_patterns" : [
        {
          "es": {
            "default_index": "logstash-*",
            "allow_url_parameter": false
          },
          "tail_interval_in_seconds": 6,
          "es_index_time_offset_in_seconds": 0,
          "display_timezone": "local",
          "display_timestamp_format": "MMM DD HH:mm:ss",
          "max_buckets": 500,
          "default_time_range_in_days" : 0,
          "max_hosts": 100,
          "max_events_to_keep_in_viewer": 5000,
          "fields" : {
            "mapping" : {
                "timestamp" : "@timestamp",
                "display_timestamp" : "@timestamp",
                "hostname" : "kubernetes.labels.app",
                "program": "kubernetes.container_name",
                "program": "kubernetes.namespace_name",
                "message": "log"
            },
            "message_format": "({{{kubernetes.pod_name}}}) | ({{{kubernetes.namespace_name}}}) | {{{log}}}"
          }
        }
      ]
    }